# Generated by Django 4.2 on 2025-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-trophy', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('institution_url', models.URLField(blank=True)),
                ('years', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('company_url', models.URLField(blank=True)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_used', models.CharField(help_text='Comma separated skills', max_length=500)),
                ('icon_class', models.CharField(default='fas fa-laptop-code', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harsha Vardhan', max_length=100)),
                ('surname', models.CharField(default='Gadde', max_length=100)),
                ('role', models.CharField(default='Full Stack Developer', max_length=100)),
                ('bio', models.TextField()),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(default='gaddeharshav@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 9392 441826', max_length=20)),
                ('location', models.CharField(default='Vijayawada, India', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('tech_stack', models.CharField(help_text='Comma separated technologies', max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='FontAwesome class (e.g., fab fa-python)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
