# Generated by Django 4.2 on 2025-12-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_text',
            field=models.TextField(default="Ready to build something extraordinary? Send me a message and let's start the conversation."),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_subtitle',
            field=models.CharField(default='Who Am I', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_title',
            field=models.CharField(default='The Developer', max_length=100),
        ),
    ]
