# Generated by Django 4.2 on 2025-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_contact_text_profile_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seo_description',
            field=models.TextField(default='Portfolio of Harsha Vardhan Gadde - Full Stack Developer specializing in Python, Django, JavaScript, and Cloud Technologies.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_keywords',
            field=models.TextField(default='Harsha Vardhan Gadde, Full Stack Developer, Python, Django, Portfolio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seo_title',
            field=models.CharField(default='Harsha Vardhan Gadde | Full Stack Developer Portfolio', max_length=200),
        ),
    ]
