# Generated by Django 5.0.1 on 2025-05-25 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Income', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Contact', models.TextField()),
                ('Amount_Paid', models.IntegerField()),
                ('Cash', models.IntegerField(default=0)),
                ('UPI', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Description', models.TextField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ghee_Coconut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Total_Amount', models.IntegerField(default=130)),
                ('Cash', models.IntegerField(default=0)),
                ('UPI', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ghee_coconut_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_range_start', models.CharField(max_length=20)),
                ('receipt_range_end', models.CharField(max_length=20)),
                ('receipts_count', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='inventory_items_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=254, unique=True)),
                ('purchase_price', models.IntegerField()),
                ('items_sale_price', models.IntegerField()),
                ('item_sold', models.IntegerField(default=0)),
                ('items_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Irumudi_bookig_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Contact', models.TextField()),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Irumudi_Price', models.IntegerField(default=380)),
                ('Irumudi_Quantity', models.IntegerField()),
                ('Booking_Date', models.DateField(default=datetime.date.today)),
                ('Schedule_Date', models.DateField()),
                ('Scheduled_Time', models.TextField()),
                ('Amount_Paid', models.IntegerField()),
                ('Balance', models.IntegerField(default=0)),
                ('Total_Amount', models.IntegerField(default=0)),
                ('Advance_Paid', models.TextField()),
                ('Balance_Clear_Date', models.DateField(blank=True, null=True)),
                ('Balance_Amount_Paid', models.IntegerField(default=0)),
                ('Balance_Amount_Payment_Mode', models.CharField(blank=True, max_length=20, null=True)),
                ('Cash', models.IntegerField(default=0)),
                ('UPI', models.IntegerField(default=0)),
                ('Balance_Receipt_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Irumudi_by_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('End_Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Total_Amount', models.IntegerField(default=130)),
                ('Cash', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Irumudi_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Items_sold_rcpt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Product_name', models.TextField()),
                ('Total_Amount', models.IntegerField()),
                ('Cash', models.IntegerField(default=0)),
                ('UPI', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maaladharane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Total_Amount', models.IntegerField(default=15)),
                ('Cash', models.IntegerField(default=0)),
                ('UPI', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maladharane_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_range_start', models.CharField(max_length=20)),
                ('receipt_range_end', models.CharField(max_length=20)),
                ('receipts_count', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materials_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('receipt_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temple_seva_receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seva_Type', models.CharField(max_length=250)),
                ('Booking_Date', models.DateField(default=datetime.date.today)),
                ('Schedule_Date', models.DateField()),
                ('Receipt_Number', models.CharField(max_length=20, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Contact', models.TextField()),
                ('Total_Amount', models.IntegerField()),
                ('Amount_Paid', models.IntegerField()),
                ('Balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UPI_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
